### PR TITLE
Cleaned up framework settings to allow unit tests to run

### PR DESCRIPTION
**Pull request by grgcombs**
Some of the settings in the framework project were preventing unit tests from running.  In particular, there was a derived data search path that was specific to the build environment at ustwo.  I also cleaned up some of the compiler warnings and conflicting build settings between the library target and the unit test target, as well as added the XCTest.framework to the unit test target's linker.

### CODE REVIEW

**Comment by alexfish** [comment]
thanks :+1: 

A nicer way to suppress the protocol warnings would be to add a compiler flag like so in the compile sources

image

**Comment by grgcombs** [comment]
That's a great flag, I hadn't used that one before, thanks!

I think the main purpose of the commit was to take care of this path that was hard-coded to one found in (your?) development environment and resulted in an inability to link for unit tests.

"\"$(SRCROOT)/../../../Library/Developer/Xcode/DerivedData/US2FormValidationFramework-dbiegtxisormauhjwlitbbkypdsr/Build/Products/Debug-iphonesimulator\"",

Everything else was really geared towards warnings.

**Comment by alexfish** [comment]
Yeah sure, must have been dragged into the project to add the framework, thanks for fixing. 

If you update that protocol fix I can merge in your PR

**Comment by grgcombs** [comment]
All fixed up now in 8af1f1bffd53223f336935848c3af8cbdf51070b. Thanks for the tip for the compiler flag!

**Comment by alexfish** [comment]
Thanks!

**Pull request merged**
