### PR TITLE
Add composite validator

### PR DESCRIPTION
**Pull request by mpurland**
Adding functionality for a composite validator to assist in situations where many validators (not necessarily conditions) will be used across controls to control validation e.g. a form.

### CODE REVIEW

**Comment by alexfish** [comment]
Nice work!

I'll take a look at this for you and get it merged in once we're all good.

**Comment by alexfish** [comment]
Sorry to be picky with the formatting with this but could you do a bit of cleanup to get this inline with the existing project styling. I know you may have your own opinion on this but i'd like to keep everything consitant throughout. 

## Curly Brackets

Could you please move all curly brackets to a new line.

#### Good

```
- (void)myMethod
{
    if(YES)
    {
        [self doSomething];
    }
}
```

#### Bad

```
- (void)myMethod {
    if(YES){
        [self doSomething];
    }
}
```

## Method Declarations

Could you please remove all spaces from your method declarations

#### Good

```
- (void)setFoo:(Bar *)foo
```

#### Bad

```
- (void) setFoo: (Bar *) foo
```

Thanks!

**Comment by mpurland** [comment]
Thanks.  I hope my changes can help the project.  Does the latest commit with the formatting changes work?

**Comment by alexfish** [comment]
That's great, thanks. 

We're pretty busy over here today but i'll make some time this weekend to have another look through and get this merged in.  Sorry for the wait!

**Comment by alexfish** [comment]
Merged!

**Comment by mpurland** [comment]
Looks great.  Thanks!

**Pull request closed without merging**
