### PR TITLE
add US2ConditionRegex and change to easy use US2ValidateTextField

### PR DESCRIPTION
**Pull request by hpyhacking**

### CODE REVIEW

**Comment by hpyhacking** [comment]
my commit in the master, If need the necessary changes to other branch please tell me. thank you~

**Comment by alexfish** [comment]
This is a nice idea, although i can't help but feel that this could be integrated into `US2Condition` at the base class layer. It doesn't seem correct having this functionality as an independent class.

My thinking is adding a regex property to the base `US2Condition` class which can be overwritten by `US2ConditionEmail` and other classes that require regex to function, much more elegant. 

Or another option is a `US2ConditionRegex` class which `US2ConditionEmail` etc is subclassed from. Personally though i prefer the first option.

What do you think @martinstolz @iceydee?

**Comment by iceydee** [comment]
Totally agree. Shouldn't impose a specific implementation with the class
name itself.

**Comment by alexfish** [comment]
Ok i've implemented the changes: https://github.com/ustwo/US2FormValidator/commit/acc4d5c3ec8830f67f6618491759aac5ba4d4fbf so will close this pull request.

@hpyhacking thanks for the original idea on this one, it's a nice feature to have in place.

**Comment by hpyhacking** [comment]
: )

**Pull request closed without merging**
