### PR TITLE
Make it easier to use US2FormValidator in projects with internal localization

### PR DESCRIPTION
**Pull request by ivanzoid**
I've renamed US2FormValidator's Localizable.strings to US2Localizable.strings and replaced all occurrences of NSLocalizedString to NSLocalizedStringFromTable.

### CODE REVIEW

**Comment by alexfish** [comment]
Thanks for this! I'll merge in your changes when i get a second later today.

**Comment by alexfish** [comment]
Just looking at this quickly it appears you have removed the old strings files and forgotten to add the new ones, could you add them in so i can merge?

**Comment by ivanzoid** [comment]
Whoops, sorry. Added now.

**Comment by alexfish** [comment]
Thanks, one more thing!

Could you update the sample project to include US2Localizable.strings, it won't build at the moment because it is looking for the old strings file.

**Comment by ivanzoid** [comment]
Alex, done!

I also think that Readme file should be updated to include instruction to drag-n-drup US2Localization.strings to the user's project file tree (or added to "Copy Bundle Resources" build phase), because otherwise it won't be copied to application's bundle and therefore localized strings won't be found at runtime.

**Comment by alexfish** [comment]
Thanks again!

I'll merge, update the readme and tag a new release.

**Pull request merged**
